# MySQL
development:
  adapter: mysql2
  encodint: utf8
  database: nukblog
  pool: 5
  username: root
  password: 
  host: localhost

test:
  adapter: mysql2
  encodint: utf8
  database: nukblog
  pool: 5
  username: root
  password: 

production:
  adapter: mysql2
  encodint: utf8
  database: nukblog
  pool: 5
  username: root
  password: 



