# MySQL
development:
  adapter: mysql2
  encodint: utf8
  database: nukblog
  pool: 5
  username: se-ichi
  password: qwer
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encodint: utf8
  database: nukblog
  pool: 5
  username: se-ichi
  password: qwer
  socket: /var/run/mysqld/mysqld.sock
#  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encodint: utf8
  database: nukblog
  pool: 5
  username: se-ichi
  password: qwer
  socket: /var/run/mysqld/mysqld.sock
#  socket: /tmp/mysql.sock



